### ISSUE TITLE
need to submit recording file, and name it properly

### ISSUE THREAD

**Issue by michaelpalumbo** [dispersionlab/gitshow8#1]
Hi @rekdtech 

Can you take care of this before class? I need to reassign write privileges to the repos and want to make sure your repo has your version of the recording file. 

I see that I named the recording file recording1.wav by mistake (is supposed to be 'recording.wav'.) Sorry about that. It's a remnant from an earlier phase of the research. 

Remember that we only want one recording in the repository, and it needs to be named recording.wav. 

Can you make sure that when you submit the recording, that it is named exactly recording.wav. The best way to do this is to preserve the git history on that filename:

if you just rename 'recording1.wav' as 'recording.wav', git will think its a new file and we'll lose its connection to all earlier versions of recording.wav. so, a trick is to use git mv:

```shell
git mv recording1.wav recording.wav
````

Then commit and push. 

Thanks!!

**Comment by rekdtech** [comment]
pretty sure it's fixed now...

**Comment by michaelpalumbo** [comment]
great!
